version: "3.8"
services:
  app:
    image: ggilman/rtlsdr-igate-docker:latest
    container_name: aprs
    restart: unless-stopped
    network_mode: bridge
   # priviliged: true
    environment:
      - MYCALL=MYCALLL #Mandatory!!
      - APRS_PASSWORD=0 #MANDATORY!!

     #Optional Entries
     # - DEVICE_INDEX=0
     # - COMMENT='Docker APRS Igate'
     # - LATITUDE=30.24344
     # - LONGITUDE=-85.61304
     # - BEACON_EVERY=10
     # - APRS_FREQUENCY=144.642M
    devices:
      - /dev/bus/usb
